-- Cliente: conta/contato, responsável financeiro.
CREATE TABLE cliente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(255)   NOT NULL,
    telefone          VARCHAR(20)    NOT NULL,
    email             VARCHAR(255),
    cpf               VARCHAR(11),
    cnpj              VARCHAR(14),
    data_nascimento   DATE,
    sexo              VARCHAR(30),
    CONSTRAINT uq_cliente_telefone UNIQUE (telefone)
);

-- Endereco: pertence a um único cliente (sem compartilhamento entre clientes).
CREATE TABLE endereco (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  BIGINT       NOT NULL REFERENCES cliente (id) ON DELETE CASCADE,
    cep         VARCHAR(9)   NOT NULL,
    rua         VARCHAR(255) NOT NULL,
    numero      VARCHAR(20)  NOT NULL,
    bairro      VARCHAR(255) NOT NULL,
    cidade      VARCHAR(255) NOT NULL,
    estado      VARCHAR(2)   NOT NULL,
    complemento VARCHAR(255)
);
CREATE INDEX idx_endereco_cliente ON endereco (cliente_id);

-- Aluno: quem recebe o serviço. Sempre tem um responsável (mesmo quando é ele próprio).
CREATE TABLE aluno (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsavel_id         BIGINT       NOT NULL REFERENCES cliente (id) ON DELETE CASCADE,
    nome                   VARCHAR(255) NOT NULL,
    data_nascimento        DATE         NOT NULL,
    sexo                   VARCHAR(30),
    observacoes            VARCHAR(1000),
    eh_proprio_responsavel BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_aluno_responsavel ON aluno (responsavel_id);

-- "No máximo um aluno titular (ehProprioResponsavel=true) por cliente" NÃO é um índice parcial
-- aqui de propósito: H2 (usado nos testes) não suporta índice único com WHERE, só Postgres.
-- A regra é garantida em AlunoService (busca-e-reaproveita o titular antes de criar outro),
-- que é o único ponto de escrita desta tabela.

-- PrecoServico: catálogo administrado pelo professor. Única fonte de preço.
-- Categorias de aula usam categoria+modalidade+tipo_contratacao (cada combinação tem um valor
-- FIXO próprio, não calculado - a tabela real de negócio não segue uma fórmula de desconto
-- uniforme, e nem toda categoria oferece todos os tamanhos de pacote).
-- EVENTO não tem esse eixo fixo - o professor cadastra quantos pacotes quiser (nome obrigatório
-- nesse caso), cada um podendo ser "sob consulta" (valor/duracao_padrao_minutos nulos).
CREATE TABLE preco_servico (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria              VARCHAR(30)    NOT NULL,
    modalidade             VARCHAR(20),
    tipo_contratacao       VARCHAR(20),
    tipo_evento            VARCHAR(30),
    nome                   VARCHAR(255),
    descricao              VARCHAR(2000),
    publico_alvo           VARCHAR(255),
    equipe                 VARCHAR(255),
    materiais              VARCHAR(1000),
    valor                  NUMERIC(10, 2) CHECK (valor IS NULL OR valor > 0),
    duracao_padrao_minutos INTEGER,
    atualizado_em          TIMESTAMP      NOT NULL DEFAULT now(),
    -- Plano (não NULLS NOT DISTINCT, que é sintaxe só do Postgres 15+): não bloqueia duas linhas
    -- EVENTO/modalidade=NULL no banco entre si, o que é o comportamento desejado agora - EVENTO
    -- pode ter várias linhas (um pacote por linha). Para as demais categorias, modalidade e
    -- tipo_contratacao nunca são nulos, então a constraint funciona normalmente.
    CONSTRAINT uq_preco_categoria_modalidade_pacote UNIQUE (categoria, modalidade, tipo_contratacao),
    CONSTRAINT ck_preco_nome_ou_modalidade CHECK (
        (categoria = 'EVENTO' AND modalidade IS NULL AND tipo_contratacao IS NULL AND nome IS NOT NULL) OR
        (categoria <> 'EVENTO' AND modalidade IS NOT NULL AND tipo_contratacao IS NOT NULL)
    )
);

-- Matricula: fechamento de um pacote (tamanho varia por categoria - ver ETipoContratacao).
-- Não existe para categoria EVENTO.
CREATE TABLE matricula (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id        BIGINT         NOT NULL REFERENCES cliente (id),
    aluno_id          BIGINT         NOT NULL REFERENCES aluno (id),
    preco_servico_id  BIGINT         NOT NULL REFERENCES preco_servico (id),
    tipo_contratacao  VARCHAR(20)    NOT NULL,
    valor_total       NUMERIC(10, 2) NOT NULL,
    aulas_contratadas INTEGER        NOT NULL CHECK (aulas_contratadas > 0),
    instrumento       VARCHAR(20),
    status            VARCHAR(20)    NOT NULL DEFAULT 'ATIVA',
    data_contratacao  TIMESTAMP      NOT NULL DEFAULT now()
);
CREATE INDEX idx_matricula_cliente ON matricula (cliente_id);
CREATE INDEX idx_matricula_aluno ON matricula (aluno_id);

-- Turma: horário de aula em grupo criado pelo professor, com código curto para as famílias
-- se matricularem. Não fixa o tamanho do pacote - cada família escolhe o seu ao entrar
-- (preço de grupo é por aluno, não uma taxa única da turma).
CREATE TABLE turma (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(10)  NOT NULL,
    categoria   VARCHAR(30)  NOT NULL,
    instrumento VARCHAR(20),
    data        DATE         NOT NULL,
    hora        TIME         NOT NULL,
    local       VARCHAR(255) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ATIVA',
    criada_em   TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_turma_codigo UNIQUE (codigo)
);

-- Agendamento: uma visita (uma aula, uma turma ou um evento). Para EVENTO, preco_servico_id
-- referencia o pacote escolhido no catálogo; valor_cobrado fica nulo só quando esse pacote é
-- "sob consulta", até o professor definir o orçamento manualmente. codigo_publico é o
-- identificador não sequencial que o cliente usa para consultar sua própria aula.
CREATE TABLE agendamento (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_publico         VARCHAR(36)    NOT NULL,
    cliente_id             BIGINT         NOT NULL REFERENCES cliente (id),
    aluno_id               BIGINT         REFERENCES aluno (id),
    matricula_id           BIGINT         REFERENCES matricula (id),
    preco_servico_id       BIGINT         REFERENCES preco_servico (id),
    turma_id               BIGINT         REFERENCES turma (id),
    categoria              VARCHAR(30)    NOT NULL,
    instrumento            VARCHAR(20),
    tipo_evento            VARCHAR(30),
    local                  VARCHAR(255),
    valor_cobrado          NUMERIC(10, 2),
    duracao_minutos        INTEGER        NOT NULL,
    data                   DATE           NOT NULL,
    hora                   TIME           NOT NULL,
    status                 VARCHAR(20)    NOT NULL DEFAULT 'AGENDADO',
    data_hora_check_in     TIMESTAMP,
    data_hora_finalizacao  TIMESTAMP,
    observacoes            VARCHAR(1000),
    data_hora_agendamento  TIMESTAMP      NOT NULL DEFAULT now(),
    CONSTRAINT uq_agendamento_codigo_publico UNIQUE (codigo_publico)
);
CREATE INDEX idx_agendamento_cliente ON agendamento (cliente_id);
CREATE INDEX idx_agendamento_matricula ON agendamento (matricula_id);
CREATE INDEX idx_agendamento_turma ON agendamento (turma_id);
CREATE INDEX idx_agendamento_data_hora ON agendamento (data, hora);

-- Músicas que o cliente pediu para não faltar num evento (lista livre, só para EVENTO).
CREATE TABLE agendamento_musica (
    agendamento_id BIGINT       NOT NULL REFERENCES agendamento (id) ON DELETE CASCADE,
    musica         VARCHAR(255) NOT NULL
);
CREATE INDEX idx_agendamento_musica_agendamento ON agendamento_musica (agendamento_id);

-- Músico parceiro: cadastro simples de músicos que o professor pode chamar para reforçar
-- eventos/turmas maiores (ver "equipe" em preco_servico) - só cadastro, sem vínculo direto
-- com agendamento ainda.
CREATE TABLE musico_parceiro (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL,
    cpf         VARCHAR(11)  NOT NULL,
    telefone    VARCHAR(20)  NOT NULL,
    instrumento VARCHAR(20)  NOT NULL,
    criado_em   TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_musico_parceiro_cpf UNIQUE (cpf)
);
