-- Anamnese de Musicoterapia: perfil clínico/terapêutico do paciente, 1:1 com aluno (preenchida
-- uma única vez, na primeira sessão - não se repete a cada agendamento).
CREATE TABLE anamnese (
    id                                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id                                BIGINT         NOT NULL REFERENCES aluno (id) ON DELETE CASCADE,

    idade                                   INTEGER,
    profissao                               VARCHAR(255),
    escolaridade                            VARCHAR(255),
    estado_civil                            VARCHAR(255),

    motivo_encaminhamento                   VARCHAR(2000),
    queixa_principal                        VARCHAR(2000),
    objetivos_paciente                      VARCHAR(2000),

    -- HistoricoClinico (embeddable)
    possui_diagnostico                      BOOLEAN,
    diagnosticos                            VARCHAR(1000),
    faz_uso_medicamentos                    BOOLEAN,
    medicamentos                            VARCHAR(1000),
    possui_acompanhamento_medico            BOOLEAN,
    especialidades_medicas                  VARCHAR(1000),
    possui_acompanhamento_psicologico       BOOLEAN,
    observacoes_acompanhamento_psicologico  VARCHAR(1000),
    possui_alergias                         BOOLEAN,
    alergias                                VARCHAR(1000),

    -- PerfilDesenvolvimento (embeddable)
    desenvolvimento                         VARCHAR(1000),
    aspectos_emocionais                     VARCHAR(1000),
    aspectos_cognitivos                     VARCHAR(1000),
    aspectos_motores                        VARCHAR(1000),
    comunicacao                             VARCHAR(1000),
    socializacao                            VARCHAR(1000),
    rotina                                  VARCHAR(1000),
    sono                                    VARCHAR(1000),
    alimentacao                             VARCHAR(1000),

    -- HistoricoMusical (embeddable)
    possui_experiencia_musical              BOOLEAN,
    descricao_experiencia_musical           VARCHAR(1000),
    instrumentos_preferidos                 VARCHAR(500),
    estilos_musicais_preferidos             VARCHAR(500),
    musicas_significativas                  VARCHAR(1000),
    possui_hipersensibilidade_sonora        BOOLEAN,
    observacoes_auditivas                   VARCHAR(1000),

    objetivos_musicoterapeuticos            VARCHAR(2000),
    observacoes_gerais                      VARCHAR(2000),

    -- ResponsavelAnamnese (embeddable) - responsável legal registrado na anamnese, independente
    -- do responsável financeiro (cliente) do aluno.
    responsavel_nome                        VARCHAR(255),
    responsavel_parentesco                  VARCHAR(255),
    responsavel_telefone                    VARCHAR(20),
    responsavel_email                       VARCHAR(255),

    -- AnamneseInfantil (embeddable) - só preenchido quando o paciente é criança.
    gestacao                                VARCHAR(1000),
    parto                                   VARCHAR(1000),
    desenvolvimento_motor                   VARCHAR(1000),
    desenvolvimento_linguagem               VARCHAR(1000),
    desenvolvimento_social                  VARCHAR(1000),
    desenvolvimento_escolar                 VARCHAR(1000),
    comportamento_casa                      VARCHAR(1000),
    comportamento_escola                    VARCHAR(1000),
    seletividade_alimentar                  VARCHAR(500),
    desfralde_concluido                     BOOLEAN,
    usa_fraldas                             BOOLEAN,
    interesses_crianca                      VARCHAR(500),
    brincadeiras_favoritas                  VARCHAR(500),

    criada_em                               TIMESTAMP      NOT NULL DEFAULT now(),

    CONSTRAINT uq_anamnese_aluno UNIQUE (aluno_id)
);
