-- Matricula ganha vínculo opcional com Turma: matrícula de turma passa a só registrar o vínculo
-- aluno<->turma + pacote escolhido (referência de preço), sem mais gerar um Agendamento por aula
-- (ver TurmaService#inscrever - AgendamentoService#criarInscricaoTurma foi removido).
ALTER TABLE matricula ADD COLUMN turma_id BIGINT REFERENCES turma (id);
CREATE INDEX idx_matricula_turma ON matricula (turma_id);

-- Backfill: matrículas de turma já existentes (fluxo antigo) são identificadas pelo turma_id já
-- gravado em pelo menos um Agendamento contra elas - preserva o vínculo já existente em vez de
-- deixá-lo só implícito no histórico de agendamentos. Subquery correlacionada (em vez de
-- UPDATE...FROM/DISTINCT ON, sintaxe Postgres-specific) para funcionar também no H2 (testes).
UPDATE matricula
SET turma_id = (
    SELECT a.turma_id
    FROM agendamento a
    WHERE a.matricula_id = matricula.id
      AND a.turma_id IS NOT NULL
    ORDER BY a.id
    LIMIT 1
)
WHERE matricula.turma_id IS NULL
  AND EXISTS (
    SELECT 1 FROM agendamento a2
    WHERE a2.matricula_id = matricula.id
      AND a2.turma_id IS NOT NULL
  );

-- TurmaOcorrencia: materializa uma ocorrência semanal específica de uma Turma SÓ quando o
-- professor de fato interage com ela (primeira transição de status) - ocorrências futuras
-- continuam "virtuais" (computadas a partir de turma.dia_semana/status, nunca armazenadas) até
-- esse momento, no mesmo espírito de Matricula.aulasRestantes / AgendamentoService#turmasNoDiaDaSemana.
-- Não há backfill aqui de propósito: o histórico de Agendamento antigo é por aluno individual,
-- não representa "a turma como compromisso único" - não há dado 1:1 não-ambíguo para migrar.
CREATE TABLE turma_ocorrencia (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turma_id              BIGINT      NOT NULL REFERENCES turma (id),
    data                  DATE        NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'AGENDADO',
    data_hora_check_in    TIMESTAMP,
    data_hora_finalizacao TIMESTAMP,
    criada_em             TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_turma_ocorrencia_turma_data UNIQUE (turma_id, data)
);
CREATE INDEX idx_turma_ocorrencia_data ON turma_ocorrencia (data);
